### ISSUE TITLE
Need instructions for S-User certificates

### ISSUE THREAD

**Issue by yvon-lavoie** [sap-commerce-tools/ccv2ctl#10]
Can you provide instructions on how to export my S-User certificate and the key into two PEM-encoded files?

I can log in into the SAP Commerce Cloud portal using my S-User account but I don't know how to generate the certfile.pem and keyfile.pem files.

**Comment by mpern** [comment]
You should be able to request your "SAP Passport" here:

https://support.sap.com/en/my-support/single-sign-on-passports.html

after you get the client certificate and key in a `pfx` file, you can extract them as described in the README:
https://github.com/sap-commerce-tools/ccv2ctl#installation

**Comment by mpern** [comment]
If you have any further questions for me, just let me know

**Comment by yvon-lavoie** [comment]
I managed to create the pem files and I followed the instructions to install ccv2ctl using go.  I also created a .ccv2ctl.yaml file in my home directory with the path to my pem files and the subscription value.  When running the following command, I get the message:

`$ ./ccv2ctl get build --all`
`invalid character '<' looking for beginning of value`

**Comment by mpern** [comment]
since other people reported similar problems (check issue #2 ):

verify that the client certificate actually works by using it for the portal login in your browser.

FYI, I'm planning to rewrite the tool anyway to use the official APIs that use a dedicated API token to authenticate (so no need anymore to simulate client-certificate single sign on)
As soon as the deployment API is available (AFAIK soon), I will work on it

**Comment by yvon-lavoie** [comment]
I tried using a different account and I got the same issue as outlined in https://github.com/sap-commerce-tools/ccv2ctl/issues/2

My original account is linked to 2 subscriptions in SAP Cloud v2, so I asked a colleague to create a new SAP Passport using his account.  However, I still got the same error.

When do you expect the new version of the tool to be available?

**Comment by mpern** [comment]
I also use my user for multiple subscriptions, so this shouldn't be the issue... 🤔 

Anyway, the Deployment API should be available very soon (first weeks of January), then I will write the new version

**Comment by mpern** [comment]
I'm closing this issue in favor of the newly released [official CLI][cli]

[cli]: https://help.sap.com/viewer/1be46286b36a4aa48205be5a96240672/SHIP/en-US/8acde53272c64efb908b9f0745498015.html
