### ISSUE TITLE
HTML-Output: Your browser does not support JavaScript or it is turned off.

### ISSUE THREAD

**Issue by cybaspace** [sap-commerce-tools/ccv2ctl#11]
I've a problem using this helpful tool.

I've installed like described, but every time I call any command, the tool answers with output listed below - which says my browser doesn't support javascript.
Do I have to setup any additional things?

Example call: `ccv2ctl get build -a`

Output:
```
Session expired, logging in...
Could not parse JSON!
API Response:
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"><meta http-equiv="pragma" content="no-cache" /></head><body style="background-color:#FFFFFF" onload="var url=window.location.hash;if(url&&0!==url.length){var anchorCookie='oucrsrflwpnjvuyjfccxgfhvd_anchor=&quot;'+encodeURIComponent(url)+'&quot;';anchorCookie=anchorCookie+'; Secure; SameSite=None';document.cookie=anchorCookie}document.forms[0].submit()"><p><script language="javascript">document.write("Please wait ...");</script></p><noscript><p>Note: Your browser does not support JavaScript or it is turned off. Press the button to proceed.</p></noscript><form method="post" action="https://ycloud.accounts.ondemand.com/saml2/idp/sso/ycloud.accounts.ondemand.com"><input type="hidden" name="SAMLRequest" value="********"/><input type="hidden" name="RelayState" value="oucrsrflwpnjvuyjfccxgfhvd"/><noscript><input type="submit" value="Continue"/></noscript></form></body></html>
invalid character '<' looking for beginning of value
```

**Comment by mpern** [comment]
hm, this looks like a problem with your login information or with the login flow.

If you use the S-user in the browser, do you need to enter a token, i.e. is two factor authentication (2fa) enabled for the user?

if it is: remove the s-user from the subscription and add it again *without* 2fa and test again.
You might also need to open a support ticket to remove the second factor completely

**Comment by cybaspace** [comment]
Thank you!
The problem was: I have three S-Users of two organizations in my SAP Universal ID. This leds to the problem, although I have logged out from universal id. But on a second computer it works fine.
I was irritated by the sentence "Your browser does not support JavaScript or it is turned off." in the output ...

**Comment by mpern** [comment]
That's because how the tool works
It simulates the Single-sign-on flow of the cloud portal, without actually using a browser or executing javascript
