### ISSUE TITLE
Add a warning or documentation to use the official SAP Commerce CLI

### ISSUE THREAD

**Issue by guiliguili** [sap-commerce-tools/ccv2ctl#12]
SAP provides an official [SAP Commerce CLI](https://help.sap.com/viewer/9116f1cfd16049c3a531bfb6a681ff77/v2011/en-US/8acde53272c64efb908b9f0745498015.html) which interacts with the [SAP Commerce API](https://help.sap.com/viewer/452dcbb0e00f47e88a69cdaeb87a925d/v2011/en-US/66abfe678b55457fab235ce8039dda71.html) to provide the same functionality as **commerce-ccv2ctl**.

As such I suggest to mark **commerce-ccv2ctl** as deprecated and link to [SAP Commerce CLI](https://help.sap.com/viewer/9116f1cfd16049c3a531bfb6a681ff77/v2011/en-US/8acde53272c64efb908b9f0745498015.html) in the [README.md](https://github.com/SAP/commerce-ccv2ctl/blob/master/README.md).

**Comment by mpern** [comment]
as soon as the cloud portal release that introduces an official API for service properties is out, I will deprecate/archive `cc2ctl`

**Comment by mpern** [comment]
new API is live:

https://help.sap.com/viewer/452dcbb0e00f47e88a69cdaeb87a925d/v2011/en-US/66abfe678b55457fab235ce8039dda71.html

**Comment by mpern** [comment]
repository archived
