### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by ghost** [sap-commerce-tools/ccv2ctl#2]
I'm not sure if SAP changed anything on their side or maybe I miss something, but I'm getting the following error trying to get a build information.

`invalid character '<' looking for beginning of value`

I checked last week and was working fine.

Regards.

**Comment by ghost** [comment]
BTW I could try to fix by myself and create a PR, but I have no idea about Go, sorry ¯\\_(ツ)_/¯

**Comment by mpern** [comment]
hm, I also get this error from time to time.

The weird part is that if I run the same command immediately again, it works:

```
> ccv2ctl get builds --all
Session expired, logging in...
invalid character '<' looking for beginning of value
> ccv2ctl get builds --all
Session expired, logging in...
[
  {
    "Code": "...",
   ...
```

Do you have a sure-fire ware to reproduce it, by any chance?

**Comment by ghost** [comment]
Hi.

I just tried several times but keep the same issue. 
I don't know what you mean with "sure-fire ware", sorry.

Thank you for your quick answer.

**Comment by mpern** [comment]
do get this error every time you try to use ccv2ctl?

**Comment by ghost** [comment]
Yep.

I'm running `./ccv2ctl --certfile certfile.pem --keyfile keyfile.pem --subscription my-subscription-id get build -a` and the result is the same all the time.

```
Session expired, logging in...
invalid character '<' looking for beginning of value
```

Could be something wrong with my cert and key files?

**Comment by mpern** [comment]
yes, that could be.

Have you tried using the certificate / SAP Passport in your browser to access the cloud portal for the subscription?

**Comment by ghost** [comment]
Sorry If I haven't answer you in so long, but I have been really busy.

I just checked to log into cloud with the certificate and as you guessed, I cannot acces, I get **HTTP Status 401 – Unauthorized**

I also tried with different ROLES for the same user but the result is the same.

So, obviously is not a problem with this awesome tool. Thank you so much.

I will try to figure out what is happening.

**Comment by dzmitryastrouski** [comment]
Hello guys,
The same story with me. Just yesterday I've created SAP PAssport and tool worked  like a charm.
But today I face the same response every time. Just a wild guess that SAP is somehow blocking requests from the tool.
I tried to reissue SAP Passport, but it doesn't help.

**Comment by ghost** [comment]
What I figured out was I cannot use different SAP account with the same email in this way in the same CCv2 account (I created a dummy SAP account just for deployment but linked with the same email as my account which was also added to the same CCv2). I don't know if that is the problem but when I had only one account I could use this tool but it started failing when I added the second dummy account.

Also you can try what @mpern told me, to log into CCv2 Portal using that certificate, if you get a 401 then could be the same issue...
