### ISSUE TITLE
Authentication is failing

### ISSUE THREAD

**Issue by ShahrzadSAP** [sap-commerce-tools/ccv2ctl#3]
Authentication is failing for us, we are getting

```./ccv2ctl get builds -a
Session expired, logging in...
invalid character '<' looking for beginning of value```

**Comment by mpern** [comment]
Have you checked issue #2?
Maybe you ran into similar problems?

**Comment by ShahrzadSAP** [comment]
we are using a technical s user and it the solutions from the other issue is not related, any thoughts ?
