### ISSUE TITLE
Some commands fail when application is commerce-cloud-datahub

### ISSUE THREAD

**Issue by bloomper** [sap-commerce-tools/ccv2ctl#4]
Hi!

Some of the commands fail when the application is commerce-cloud-datahub rather than commerce-cloud, e.g. get all builds. The reason is that commerce-cloud is hardcoded in two places, types.go and portalclient.go. It needs to be configurable unless it can be picked up via the subscription.

Also, it would be great if one could reference a build via its name rather than the code but I guess that is due to how the portal works.

Cheers,
Anders

**Comment by mpern** [comment]
I don't plan to support the datahub version, but feel free to submit a PR that implements switching the application with a command line flag
