### ISSUE TITLE
Subscription not set!

### ISSUE THREAD

**Issue by ShahrzadSAP** [sap-commerce-tools/ccv2ctl#5]
I have the certfile.pem and keyfile.pem and I added .ccv2ctl.yml in /home/jenkins directory and it has the right subscript but I am still getting `Subscription not set!` for the command `ccv2ctl get build --all`.

**Comment by mpern** [comment]
check the readme ;)

make sure that you have uncommented the `subscription:` line in your `.ccv2ctl.yml` or add the command line flag `--subscpription` when invoking `ccv2ctl`
