### ISSUE TITLE
Tools sometimes fails with "invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by bloomper** [sap-commerce-tools/ccv2ctl#6]
The tool, at least when creating a build, fails randomly with the error message:

invalid character '<' looking for beginning of value

My guess is that the portal responds with an HTML structure rather than the expected JSON structure. It would be good if the tool would retry the operation or at least handle the error.

**Comment by mpern** [comment]
Implementing a retry mechanism is a good idea in general, but I would rather tackle it after all official APIs are released.

see also #8

**Comment by mpern** [comment]
Official CLI released: https://help.sap.com/viewer/1be46286b36a4aa48205be5a96240672/SHIP/en-US/8acde53272c64efb908b9f0745498015.html
