### ISSUE TITLE
"Data Migration Mode" support

### ISSUE THREAD

**Issue by sgoian** [sap-commerce-tools/ccv2ctl#7]
Hi Marcus, 
SAP CCv2 portal recently got an update, which now requires a mandatory new attribute for each deployment "Data Migration Mode", see #5 at https://help.sap.com/viewer/0fa6bcf4736c46f78c248512391eb467/SHIP/en-US/72e126a98eb14b668709be9946070e5c.html
Can this be added to ccv2ctl?
Regards and thanks for the tool!
Sorin

**Comment by mpern** [comment]
thanks for alerting me to the changed API!

I'm on it...

**Comment by mpern** [comment]
Check out the new release:

https://github.com/sap-commerce-tools/ccv2ctl/releases/tag/v0.6.0
