### ISSUE TITLE
Migrate to official public API

### ISSUE THREAD

**Issue by mpern** [sap-commerce-tools/ccv2ctl#8]
Instead of simulating the interactions of the cloud portal, use the newly released public API + API token

https://help.sap.com/viewer/0fa6bcf4736c46f78c248512391eb467/SHIP/en-US/a1db2e0af60247189783184c94ca3773.html

**Comment by sgoian** [comment]
Hi Markus, is there going to be a "Deployment" set of APIs as well, do you know?

**Comment by mpern** [comment]
Yes, but I don’t know when it will be released.
I hope until the end of the year

Am Donnerstag, 7. November 2019 schrieb sgoian <notifications@github.com>:

**Comment by sgoian** [comment]
I see. So is your aim then the act as a proxy for the time being?
Will I be able to use your tool, to both kick a build through it as a proxy to the new official APIs and to kick a deployment via the simulated interaction?

**Comment by mpern** [comment]
I think that would be a way to handle it.

For builds go via the official API, but for deployments use the current implementation until the official API is released

**Comment by mpern** [comment]
Official CLI released: 

https://help.sap.com/viewer/1be46286b36a4aa48205be5a96240672/SHIP/en-US/8acde53272c64efb908b9f0745498015.html
